In [124]:
from sklearn.linear_model import LogisticRegression
import pandas as pd
import numpy as np
from sklearn import preprocessing
data=pd.read_csv("training_titanic_x_y_train.csv")
df1=data.copy()
df1.drop(['Name'],axis=1,inplace=True)
df1.drop(['Ticket'],axis=1,inplace=True)
df1.drop(["Cabin"],axis=1,inplace=True)
df1.drop(["Survived"],axis=1,inplace=True)

df1.Embarked.dropna(inplace=True)
#df1.Age.fillna("0",inplace=True)
df1["Age"]=df1.groupby(['Pclass','Sex'])['Age'].apply(lambda x:x.fillna(x.median()))

df1.loc[df1['Sex']=='female','Sex']=0
df1.loc[df1['Sex']=='male','Sex']=1
df1.loc[df1['Embarked'].isna(),'Embarked']='S'
df1.loc[df1['Embarked']=='S','Embarked']=1
df1.loc[df1['Embarked']=='Q','Embarked']=2
df1.loc[df1['Embarked']=='C','Embarked']=3
df1

Pclass Sex   Age  SibSp  Parch     Fare Embarked
0         2   0  29.0      1      0  26.0000        1
1         3   1  26.0      0      0   8.0500        1
2         2   1  39.0      0      0  26.0000        1
3         3   0  29.0      0      4  21.0750        1
4         3   1  25.0      0      0   7.0500        1
..      ...  ..   ...    ...    ...      ...      ...
663       2   0  17.0      0      0  10.5000        1
664       3   1  26.0      0      0   7.7500        2
665       3   1  32.0      0      0  56.4958        1
666       3   0  22.0      0      0   9.8375        1
667       3   0  22.0      1      0  15.5000        2

[668 rows x 7 columns]

In [125]:
df1.isnull().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [34]:
data

Pclass                                            Name     Sex   Age  \
0         2   Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0   
1         3               Williams, Mr. Howard Hugh "Harry"    male   NaN   
2         2  Morley, Mr. Henry Samuel ("Mr Henry Marshall")    male  39.0   
3         3     Palsson, Mrs. Nils (Alma Cornelia Berglund)  female  29.0   
4         3                          Sutehall, Mr. Henry Jr    male  25.0   
..      ...                                             ...     ...   ...   
663       2                             Ilett, Miss. Bertha  female  17.0   
664       3                        Morrow, Mr. Thomas Rowan    male   NaN   
665       3                                   Bing, Mr. Lee    male  32.0   
666       3                     Strandberg, Miss. Ida Sofia  female  22.0   
667       3                  Murphy, Miss. Katherine "Kate"  female   NaN   

     SibSp  Parch           Ticket     Fare Cabin Embarked  Survived  
0        1      0           228414  26.0000   NaN        S         1  
1        0      0         A/5 2466   8.0500   NaN        S         0  
2        0      0           250655  26.0000   NaN        S         0  
3        0      4           349909  21.0750   NaN        S         0  
4        0      0  SOTON/OQ 392076   7.0500   NaN        S         0  
..     ...    ...              ...      ...   ...      ...       ...  
663      0      0       SO/C 14885  10.5000   NaN        S         1  
664      0      0           372622   7.7500   NaN        Q         0  
665      0      0             1601  56.4958   NaN        S         1  
666      0      0             7553   9.8375   NaN        S         0  
667      1      0           367230  15.5000   NaN        Q         1  

[668 rows x 11 columns]

In [126]:
df=np.array(df1)
scaling=preprocessing.StandardScaler()
scaling.fit(df)
df=scaling.transform(df)
target=np.array(data['Survived'])
target
# from sklearn import model_selection
# X_train,X_test,Y_train,Y_test=model_selection.train_test_split(df,target)

array([1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,

In [149]:
clf=LogisticRegression(multi_class='ovr')
clf.fit(df,target)

LogisticRegression(multi_class='ovr')

In [150]:
clf.predict(df)

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,

In [151]:
clf.predict_proba(df)


array([[0.20737614, 0.79262386],
       [0.88184407, 0.11815593],
       [0.80229712, 0.19770288],
       ...,
       [0.90117314, 0.09882686],
       [0.30969498, 0.69030502],
       [0.34267469, 0.65732531]])

In [152]:
clf.score(df,target)

0.7934131736526946

In [133]:
test=pd.read_csv('test_titanic_x_test.csv')
df1=test.copy()
df1.drop(['Name'],axis=1,inplace=True)
df1.drop(['Ticket'],axis=1,inplace=True)
df1.drop(["Cabin"],axis=1,inplace=True)
#df1.drop(["Survived"],axis=1,inplace=True)

df1.Embarked.dropna(inplace=True)
#df1.Age.fillna("0",inplace=True)
df1["Age"]=df1.groupby(['Pclass','Sex'])['Age'].apply(lambda x:x.fillna(x.median()))

df1.loc[df1['Sex']=='female','Sex']=0
df1.loc[df1['Sex']=='male','Sex']=1
df1.loc[df1['Embarked'].isna(),'Embarked']='S'
df1.loc[df1['Embarked']=='S','Embarked']=1
df1.loc[df1['Embarked']=='Q','Embarked']=2
df1.loc[df1['Embarked']=='C','Embarked']=3
df1

Pclass Sex    Age  SibSp  Parch      Fare Embarked
0         2   1   8.00      1      1   36.7500        1
1         1   0  49.00      0      0   25.9292        1
2         3   1  23.75      0      0    7.7375        2
3         2   0  24.00      2      1   27.0000        1
4         1   1  36.00      0      0   26.2875        1
..      ...  ..    ...    ...    ...       ...      ...
218       3   1  20.00      1      0    7.9250        1
219       1   1  45.00      0      0   26.5500        1
220       1   0  17.00      1      0  108.9000        3
221       3   1  43.00      0      0    6.4500        1
222       2   1  36.50      0      2   26.0000        1

[223 rows x 7 columns]

In [137]:
test_arr=np.array(df1)
test_arr=scaling.transform(test_arr)
d=clf.predict(test_arr)

In [138]:
np.savetxt('titanic_prediction.csv',d,fmt='%1.5f',delimiter=',')